-- Inserting into search_functions table
INSERT INTO `search_functions` (`created_at`, `id`, `key`, `updated_at`, `url`, `visible_for`) VALUES
(NULL, '1', 'Dashboard', NULL, 'admin/dashboard', 'admin'),
(NULL, '2', 'Order All', NULL, 'admin/orders/list/all', 'admin'),
(NULL, '3', 'Order Pending', NULL, 'admin/orders/list/pending', 'admin'),
(NULL, '4', 'Order Processed', NULL, 'admin/orders/list/processed', 'admin'),
(NULL, '5', 'Order Delivered', NULL, 'admin/orders/list/delivered', 'admin'),
(NULL, '6', 'Order Returned', NULL, 'admin/orders/list/returned', 'admin'),
(NULL, '7', 'Order Failed', NULL, 'admin/orders/list/failed', 'admin'),
(NULL, '8', 'Brand Add', NULL, 'admin/brand/add-new', 'admin'),
(NULL, '9', 'Brand List', NULL, 'admin/brand/list', 'admin'),
(NULL, '10', 'Banner', NULL, 'admin/banner/list', 'admin'),
(NULL, '11', 'Category', NULL, 'admin/category/view', 'admin'),
(NULL, '12', 'Sub Category', NULL, 'admin/category/sub-category/view', 'admin'),
(NULL, '13', 'Sub sub category', NULL, 'admin/category/sub-sub-category/view', 'admin'),
(NULL, '14', 'Attribute', NULL, 'admin/attribute/view', 'admin'),
(NULL, '15', 'Product', NULL, 'admin/product/list', 'admin'),
(NULL, '16', 'Coupon', NULL, 'admin/coupon/add-new', 'admin'),
(NULL, '17', 'Custom Role', NULL, 'admin/custom-role/create', 'admin'),
(NULL, '18', 'Employee', NULL, 'admin/employee/add-new', 'admin'),
(NULL, '19', 'Seller', NULL, 'admin/sellers/seller-list', 'admin'),
(NULL, '20', 'Contacts', NULL, 'admin/contact/list', 'admin'),
(NULL, '21', 'Flash Deal', NULL, 'admin/deal/flash', 'admin'),
(NULL, '22', 'Deal of the day', NULL, 'admin/deal/day', 'admin'),
(NULL, '23', 'Language', NULL, 'admin/business-settings/language', 'admin'),
(NULL, '24', 'Mail', NULL, 'admin/business-settings/mail', 'admin'),
(NULL, '25', 'Shipping method', NULL, 'admin/business-settings/shipping-method/add', 'admin'),
(NULL, '26', 'Currency', NULL, 'admin/currency/view', 'admin'),
(NULL, '27', 'Payment method', NULL, 'admin/business-settings/payment-method', 'admin'),
(NULL, '28', 'SMS Gateway', NULL, 'admin/business-settings/sms-gateway', 'admin'),
(NULL, '29', 'Support Ticket', NULL, 'admin/support-ticket/view', 'admin'),
(NULL, '30', 'FAQ', NULL, 'admin/helpTopic/list', 'admin'),
(NULL, '31', 'About Us', NULL, 'admin/business-settings/about-us', 'admin'),
(NULL, '32', 'Terms and Conditions', NULL, 'admin/business-settings/terms-condition', 'admin'),
(NULL, '33', 'Web Config', NULL, 'admin/business-settings/web-config', 'admin');

