-- Inserting into search_functions table
INSERT INTO `search_functions` (`id`, `key`, `url`, `visible_for`, `created_at`, `updated_at`) VALUES
('1', 'Dashboard', 'admin/dashboard', 'admin', NULL, NULL),
('2', 'Order All', 'admin/orders/list/all', 'admin', NULL, NULL),
('3', 'Order Pending', 'admin/orders/list/pending', 'admin', NULL, NULL),
('4', 'Order Processed', 'admin/orders/list/processed', 'admin', NULL, NULL),
('5', 'Order Delivered', 'admin/orders/list/delivered', 'admin', NULL, NULL),
('6', 'Order Returned', 'admin/orders/list/returned', 'admin', NULL, NULL),
('7', 'Order Failed', 'admin/orders/list/failed', 'admin', NULL, NULL),
('8', 'Brand Add', 'admin/brand/add-new', 'admin', NULL, NULL),
('9', 'Brand List', 'admin/brand/list', 'admin', NULL, NULL),
('10', 'Banner', 'admin/banner/list', 'admin', NULL, NULL),
('11', 'Category', 'admin/category/view', 'admin', NULL, NULL),
('12', 'Sub Category', 'admin/category/sub-category/view', 'admin', NULL, NULL),
('13', 'Sub sub category', 'admin/category/sub-sub-category/view', 'admin', NULL, NULL),
('14', 'Attribute', 'admin/attribute/view', 'admin', NULL, NULL),
('15', 'Product', 'admin/product/list', 'admin', NULL, NULL),
('16', 'Coupon', 'admin/coupon/add-new', 'admin', NULL, NULL),
('17', 'Custom Role', 'admin/custom-role/create', 'admin', NULL, NULL),
('18', 'Employee', 'admin/employee/add-new', 'admin', NULL, NULL),
('19', 'Seller', 'admin/sellers/seller-list', 'admin', NULL, NULL),
('20', 'Contacts', 'admin/contact/list', 'admin', NULL, NULL),
('21', 'Flash Deal', 'admin/deal/flash', 'admin', NULL, NULL),
('22', 'Deal of the day', 'admin/deal/day', 'admin', NULL, NULL),
('23', 'Language', 'admin/business-settings/language', 'admin', NULL, NULL),
('24', 'Mail', 'admin/business-settings/mail', 'admin', NULL, NULL),
('25', 'Shipping method', 'admin/business-settings/shipping-method/add', 'admin', NULL, NULL),
('26', 'Currency', 'admin/currency/view', 'admin', NULL, NULL),
('27', 'Payment method', 'admin/business-settings/payment-method', 'admin', NULL, NULL),
('28', 'SMS Gateway', 'admin/business-settings/sms-gateway', 'admin', NULL, NULL),
('29', 'Support Ticket', 'admin/support-ticket/view', 'admin', NULL, NULL),
('30', 'FAQ', 'admin/helpTopic/list', 'admin', NULL, NULL),
('31', 'About Us', 'admin/business-settings/about-us', 'admin', NULL, NULL),
('32', 'Terms and Conditions', 'admin/business-settings/terms-condition', 'admin', NULL, NULL),
('33', 'Web Config', 'admin/business-settings/web-config', 'admin', NULL, NULL);

